services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
  database:
    image: "postgres:14"
    restart: always
    environment:
      POSTGRES_DB: challengedb
      POSTGRES_PASSWORD: senhasupersecretaimpossiveldescobrir
      POSTGRES_USER: usuariosupremo
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "usuariosupremo", "-d", "challengedb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres: